test_app/config/routes.rb
Rails.application.routes.draw do
  resources :addto_books
  resources :books
	
  get 'books/delete'
  root 'books#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

test_app/app/models/addto_book.rb
class AddtoBook < ApplicationRecord
end

test_app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

test_app/app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true
  validates :author, presence: true
  validates :price, presence: true
  validates :date, presence: true
end

test_app/app/controllers/addto_books_controller.rb
class AddtoBooksController < ApplicationController
  before_action :set_addto_book, only: %i[ show edit update destroy ]

  # GET /addto_books or /addto_books.json
  def index
    @addto_books = AddtoBook.all
  end

  # GET /addto_books/1 or /addto_books/1.json
  def show
  end

  # GET /addto_books/new
  def new
    @addto_book = AddtoBook.new
  end

  # GET /addto_books/1/edit
  def edit
  end

  # POST /addto_books or /addto_books.json
  def create
    @addto_book = AddtoBook.new(addto_book_params)

    respond_to do |format|
      if @addto_book.save
        format.html { redirect_to addto_book_url(@addto_book), notice: "Addto book was successfully created." }
        format.json { render :show, status: :created, location: @addto_book }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @addto_book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /addto_books/1 or /addto_books/1.json
  def update
    respond_to do |format|
      if @addto_book.update(addto_book_params)
        format.html { redirect_to addto_book_url(@addto_book), notice: "Addto book was successfully updated." }
        format.json { render :show, status: :ok, location: @addto_book }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @addto_book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /addto_books/1 or /addto_books/1.json
  def destroy
    @addto_book.destroy

    respond_to do |format|
      format.html { redirect_to addto_books_url, notice: "Addto book was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_addto_book
      @addto_book = AddtoBook.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def addto_book_params
      params.require(:addto_book).permit(:author, :price, :date)
    end
end

test_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

test_app/app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: %i[ show edit update destroy ]

  # GET /books or /books.json
  def index
    @books = Book.all
  end

  # GET /books/1 or /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books or /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to book_url(@book), notice: "Book was successfully created." }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1 or /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to book_url(@book), notice: "Book was successfully updated." }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end
	
  def delete
	@book = Book.find(params[:id])
  end
  
  # DELETE /books/1 or /books/1.json
  def destroy
	@book = Book.find(params[:id])
	@book.destroy
	redirect_to(books_path)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def book_params
      params.require(:book).permit(:title, :author, :price, :date)
    end
end

test_app/app/helpers/addto_books_helper.rb
module AddtoBooksHelper
end

test_app/app/helpers/application_helper.rb
module ApplicationHelper
end

test_app/app/helpers/books_helper.rb
module BooksHelper
end

test_app/app/views/addto_books/_form.html.erb
<%= form_with(model: addto_book) do |form| %>
  <% if addto_book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(addto_book.errors.count, "error") %> prohibited this addto_book from being saved:</h2>

      <ul>
        <% addto_book.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :author %>
    <%= form.text_field :author %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price %>
  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.date_select :date %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

test_app/app/views/addto_books/edit.html.erb
<h1>Editing Addto Book</h1>

<%= render 'form', addto_book: @addto_book %>

<%= link_to 'Show', @addto_book %> |
<%= link_to 'Back', addto_books_path %>

test_app/app/views/addto_books/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Addto Books</h1>

<table>
  <thead>
    <tr>
      <th>Author</th>
      <th>Price</th>
      <th>Date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @addto_books.each do |addto_book| %>
      <tr>
        <td><%= addto_book.author %></td>
        <td><%= addto_book.price %></td>
        <td><%= addto_book.date %></td>
        <td><%= link_to 'Show', addto_book %></td>
        <td><%= link_to 'Edit', edit_addto_book_path(addto_book) %></td>
        <td><%= link_to 'Destroy', addto_book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Addto Book', new_addto_book_path %>

test_app/app/views/addto_books/new.html.erb
<h1>New Addto Book</h1>

<%= render 'form', addto_book: @addto_book %>

<%= link_to 'Back', addto_books_path %>

test_app/app/views/addto_books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Author:</strong>
  <%= @addto_book.author %>
</p>

<p>
  <strong>Price:</strong>
  <%= @addto_book.price %>
</p>

<p>
  <strong>Date:</strong>
  <%= @addto_book.date %>
</p>

<%= link_to 'Edit', edit_addto_book_path(@addto_book) %> |
<%= link_to 'Back', addto_books_path %>

test_app/app/views/books/_form.html.erb
<%= form_with(model: book) do |form| %>
  <% if book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
        <% book.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <div class="field">
  	<%= form.label :author %>
    <%= form.text_field :author %>
  </div>
  <div class="field">
  	<%= form.label :price %>
    <%= form.text_field :price %>
  </div>
    <div class="field">
  	<%= form.label :date %>
    <%= form.datetime_select :date, :include_blank => true %>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

test_app/app/views/books/delete.html.erb
<%= link_to 'Back', books_path %>

<div class="books delete">
	<h2> Delete Book </h2>
	<%=form_for(@book, :method => 'delete') do |f| &>
	
	<p> Are you sure you want to permanently delete this subject?</p>
	<p><%= @book.title %></p>
	
	<div class="form-buttons">
		<%= f.submit("Delete Book") %>
	</div>
	
	<% end %>
</div>

test_app/app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

test_app/app/views/books/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Books</h1>
<table>
  <thead>
    <tr>
      <th>Title</th>
	  <th>Author</th>
	  <th>Price</th>
	  <th>Published</th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.title %></td>
		<td><%= book.author %></td>
		<td><%= book.price %></td>
		<td><%= book.date %></td>
        <td><%= link_to 'Show', book %></td>
        <td><%= link_to 'Edit', edit_book_path(book) %></td>
        <td><%= link_to 'Delete', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Book', new_book_path %>

test_app/app/views/books/new.html.erb
<h1>New Book</h1>

<%= render 'form', book: @book %>
<%= link_to 'Back', books_path %>

test_app/app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @book.title %>
</p>
<p>
  <strong>Author:</strong>
  <%= @book.author %>
</p>
<p>
  <strong>Price:</strong>
  <%= @book.price %>
</p>
<p>
  <strong>Published Date:</strong>
  <%= @book.date %>
</p>

<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>

test_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>